"use client";

import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";
import { Card } from "@/components/ui/Card";
import { problemSubmissionSchema } from "@/lib/validation/problem";
import type { AIPlan } from "@/lib/ai/schema";

type FormErrors = Record<string, string>;

export function ProblemForm() {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [location, setLocation] = useState("");
  const [imageUrl, setImageUrl] = useState("");
  const [errors, setErrors] = useState<FormErrors>({});
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<AIPlan | null>(null);
  const [planError, setPlanError] = useState<string | null>(null);

  function validate(): boolean {
    const result = problemSubmissionSchema.safeParse({ title, description, location, imageUrl });
    if (!result.success) {
      const fieldErrors: FormErrors = {};
      for (const issue of result.error.issues) {
        const field = issue.path[0]?.toString();
        if (field && !fieldErrors[field]) {
          fieldErrors[field] = issue.message;
        }
      }
      setErrors(fieldErrors);
      return false;
    }
    setErrors({});
    return true;
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    setLoading(true);
    setPlanError(null);
    setPlan(null);

    try {
      const response = await fetch("/api/ai/plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title, description, location, imageUrl }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.detail || data.error || "Failed to generate plan");
      }

      setPlan(data.plan);
    } catch (err) {
      setPlanError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-8">
      <Card>
        <form onSubmit={handleSubmit} className="space-y-5">
          <h2 className="text-lg font-semibold text-gray-900">
            Report a Civic Problem
          </h2>

          <Input
            label="Title"
            placeholder="e.g. Street flooding beside the school"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            error={errors.title}
          />

          <Textarea
            label="Description"
            placeholder="Describe the problem in detail. What happens? Who is affected? When does it occur?"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            error={errors.description}
          />

          <Input
            label="Location"
            placeholder="e.g. Street beside City School, Sector 4"
            value={location}
            onChange={(e) => setLocation(e.target.value)}
            error={errors.location}
          />

          <Input
            label="Image URL (optional)"
            placeholder="https://example.com/photo.jpg"
            value={imageUrl}
            onChange={(e) => setImageUrl(e.target.value)}
            error={errors.imageUrl}
          />

          <Button type="submit" disabled={loading}>
            {loading ? "Generating Plan..." : "Generate Plan"}
          </Button>
        </form>
      </Card>

      {planError && (
        <Card className="border-red-200 bg-red-50">
          <p className="text-sm font-medium text-red-800">
            Failed to generate plan
          </p>
          <p className="mt-1 text-sm text-red-600">{planError}</p>
        </Card>
      )}

      {plan && (
        <Card className="border-emerald-200">
          <h3 className="text-lg font-semibold text-gray-900">
            AI Draft — Review Before Confirming
          </h3>
          <p className="mt-1 text-xs text-gray-500">
            This is a draft generated by AI. Review, edit, and confirm before
            creating an official project.
          </p>

          <div className="mt-4 space-y-4">
            <div>
              <h4 className="text-sm font-semibold text-gray-700">
                Problem Summary
              </h4>
              <p className="text-sm text-gray-600">{plan.problemSummary}</p>
            </div>

            <div>
              <h4 className="text-sm font-semibold text-gray-700">
                Affected Groups
              </h4>
              <ul className="mt-1 list-disc pl-5 text-sm text-gray-600">
                {plan.affectedGroups.map((g) => (
                  <li key={g}>{g}</li>
                ))}
              </ul>
            </div>

            <div>
              <h4 className="text-sm font-semibold text-gray-700">Objective</h4>
              <p className="text-sm text-gray-600">{plan.objective}</p>
            </div>

            <div>
              <h4 className="text-sm font-semibold text-gray-700">Tasks</h4>
              <ul className="mt-1 space-y-1">
                {plan.tasks.map((t, i) => (
                  <li
                    key={i}
                    className="text-sm text-gray-600"
                  >
                    <span className="font-medium">{t.title}</span> — {t.ownerRole}
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h4 className="text-sm font-semibold text-gray-700">KPIs</h4>
              <ul className="mt-1 space-y-1">
                {plan.kpis.map((k, i) => (
                  <li key={i} className="text-sm text-gray-600">
                    <span className="font-medium">{k.name}</span> ({k.unit}) —{" "}
                    {k.baseline === null ? "Unmeasured" : k.baseline}
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h4 className="text-sm font-semibold text-gray-700">
                Evidence Required
              </h4>
              <ul className="mt-1 list-disc pl-5 text-sm text-gray-600">
                {plan.evidenceRequirements.map((e) => (
                  <li key={e}>{e}</li>
                ))}
              </ul>
            </div>
          </div>

          <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center">
            <Button disabled title="Project persistence is coming in the next build phase.">
              Confirm &amp; Create Project
            </Button>
            <Button variant="outline" onClick={() => setPlan(null)}>
              Discard Draft
            </Button>
          </div>
          <p className="mt-3 text-xs text-gray-500">
            Project persistence, editing, and confirmation are the next build
            phase. For now you can review the AI draft and generate a new one.
          </p>
        </Card>
      )}
    </div>
  );
}
